In [23]:
import numpy as np

array_3by5 = np.ones((3,5))
print(array_3by5)

# note that the first index is row, and the 3nd is column, same as in matlab
array_3by5[1,2] = 2
print("change the 2nd row 3rd colum value to 2")
print(array_3by5)
print("shape of the array")
print(array_3by5.shape)

array_3by2 = np.ones((3,2))

array_hstack = np.hstack((array_3by5, array_3by2))
print(array_hstack)

# the tricky thing about np.array is if you select the 1st colum, it will return a row array.
# so you cannot use hstack with it.
print(array_3by5[:,1])
# if you transpose it... sorry, it is still a row array. wtf!!!
print(array_3by5[:,1].T)

# you can vtack the row with the transposed array.
array_hstack = np.vstack((array_3by5[:,1], array_3by2.T))
print("array hstack:")
print(array_hstack)

# or you can vtack the row to make it column and then hstack the column with the array:
array_vstack = np.hstack( (np.vstack(array_3by5[:,1]), array_3by2) )
print(array_vstack)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
change the 2nd row 3rd colum value to 2
[[1. 1. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 1. 1.]]
shape of the array
(3, 5)
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 2. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[1. 1. 1.]
[1. 1. 1.]
array hstack:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
